import {SampleBottle} from './samplebottle';

export const SAMPLEBOTTLES: SampleBottle[] = [
  {id: 1,
    sample: 1,
    bottle: 20008029,
    bottle_string: 'WIT287CHJ',
    analysis_type: 41,
    filter_type: 26,
    volume_filtered: 3,
    preservation_type: 8,
    preservation_volume: 4,
    preservation_acid: 8064,
    preservation_comment: 'Test 1'},
  {id: 2,
    sample: 1,
    bottle: 20008028,
    bottle_string: 'WIT343CHJ',
    analysis_type: 42,
    filter_type: 26,
    volume_filtered: 5,
    preservation_type: 8,
    preservation_volume: 6,
    preservation_acid: 8064,
    preservation_comment: 'Test 2'},
  {id: 3,
    sample: 1,
    bottle: 20008027,
    bottle_string: 'WIT193CHJ',
    analysis_type: 23,
    filter_type: 26,
    volume_filtered: 7,
    preservation_type: 8,
    preservation_volume: 8,
    preservation_acid: 8064,
    preservation_comment: 'Test 3'},
  {id: 4,
    sample: 2,
    bottle: 20008026,
    bottle_string: 'GLR525CHJ',
    analysis_type: 36,
    filter_type: 26,
    volume_filtered: 9,
    preservation_type: 8,
    preservation_volume: 10,
    preservation_acid: 8064,
    preservation_comment: 'Test 4'},
  {id: 5,
    sample: 2,
    bottle: 20008025,
    bottle_string: 'WIT061CHJ',
    analysis_type: 41,
    filter_type: 26,
    volume_filtered: 11,
    preservation_type: 8,
    preservation_volume: 12,
    preservation_acid: 8064,
    preservation_comment: 'Test 5'}
];
